# @sidebar midi
class USB_MIDI_HOST
  DISCONNECTED: Integer
  INITIALIZING: Integer
  CONNECTED: Integer
  ERROR: Integer

  CIN_NOTE_OFF: Integer
  CIN_NOTE_ON: Integer
  CIN_CONTROL_CHANGE: Integer
  CIN_PROGRAM_CHANGE: Integer
  CIN_PITCH_BEND: Integer
  CIN_SINGLE_BYTE: Integer
  CIN_SYSEX_START: Integer
  CIN_SYSEX_END_2: Integer
  CIN_SYSEX_END_3: Integer

  def self.instance: () -> USB_MIDI_HOST
  def self.new: () -> instance

  def transport_id: () -> Integer
  def status: () -> Integer
  def connected?: () -> bool
  def device_info: () -> (Hash[Symbol, untyped] | nil)
  def open_device: () -> (USB_MIDI_HOST | nil)
  def send_packet: (Integer cable, Integer cin, Integer midi1, Integer midi2, Integer midi3) -> Integer
  def bytes_available: () -> Integer
  def read_available: () -> nil

  private
  def _init: () -> Integer
  def _get_status: () -> Integer
  def _get_device_info: () -> (Hash[Symbol, untyped] | nil)
  def _send_packet: (Integer, Integer, Integer, Integer, Integer) -> Integer
end
